language: go

go:
  - 1.3
  - 1.4

install:
  - export GOPATH="$HOME/gopath"
  - mkdir -p "$GOPATH/src/github.com/brianbowden"
  - mv "$TRAVIS_BUILD_DIR" "$GOPATH/src/github.com/brianbowden/oauth2"
  - go get -v -t -d github.com/brianbowden/oauth2...

script:
  - go test -v github.com/brianbowden/oauth2/...
